### ISSUE TITLE
Mac OSX?

### ISSUE THREAD

**Issue by brent-hoover** [jeroenpeeters/docker-network-containers#1]
This is more a question than an issue, but has anybody been able to get this to work on OSX? When running it I get the error "I do not know how to setup interface en0.". Then it continues on with "waiting for public ip to be bound" which never completes.

**Comment by jeroenpeeters** [comment]
Hi and thanks for showing interest in my scripts :+1: 

For bridging the network interfaces I rely on https://github.com/jpetazzo/pipework. So any issues with bridging the interfaces should be directed there. I checked any issues related to OSX, and it seems that OSX is not and will not be supported by pipework (see https://github.com/jpetazzo/pipework/issues/99).

That being said, it seems that your issue is quite different. Are you sure that interface on the host is named 'en0'?

**Comment by brent-hoover** [comment]
Yes.

»» ifconfig

en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    ether 80:e6:50:1b:7b:06
    inet6 fe80::82e6:50ff:fe1b:7b06%en0 prefixlen 64 scopeid 0x4
    **inet 10.0.1.198** netmask 0xffff0000 broadcast 10.0.255.255
    nd6 options=1<PERFORMNUD>
    media: autoselect
    status: active

**Comment by jeroenpeeters** [comment]
Just to clarify for any future users, Pipework WILL NOT WORK on OSX. See https://github.com/jpetazzo/pipework/issues/99#issuecomment-88307180.

Therefore my Docker Network Container scripts will also not work on OSX. On OSX docker is ran inside a virtual box virtual. This apparently complicates things (such as creating network bridges) too much.
If at any time pipework will support OSX, my scripts will do too. Until then it will not work unfortunately.

Suggestion: Run Linux (native or inside your own virtual).
