### ISSUE TITLE
Thanks! Yours is the ONLY one that works!

### ISSUE THREAD

**Issue by symgryph** [jeroenpeeters/docker-network-containers#2]
I tried a number of other ones, and yours is the ONLY one that works. How do you do that sorcery? I looked around and couldn't wrap how you are doing things.

Thomas

**Comment by jeroenpeeters** [comment]
Thanks, how can I help you understand the inner workings better? It basically works like this:
1. The script grabs the ports exposed by the docker service container
2. The generated script forwards these ports from its own IP to the IP of the service container using iptables forwarding
3. This script is executing -inside- the network container. Because the network container is linked to the service container, the network container can read the IP of the service container (called private_server) from its hosts file.

That is basically all that the network container does. How does this network container gets its ip?

For this I use the pipework script. That script creates a virtual network device inside the network container that is bridged with the network device of the host. Because of this it can access the DHCP service from the network.

The script waits until an IP is assigned to the container, and then exits. You can also read the IP from the log if you do docker logs 'container-name-or-id'.

Please let me know if anything is still unclear. Thanks for using my script!

**Comment by symgryph** [comment]
Which os did you use as a base for 'your' container. Its quite clever using
it as a bridge between the two networking worlds.

Thomas

On Sun, Feb 22, 2015 at 4:37 PM, Jeroen Peeters notifications@github.com
wrote:

> Thanks, how can I help you understand the inner workings better? It
> basically works like this:
> 1. The script grabs the ports exposed by the docker service container
> 2. The generated script forwards these ports from its own IP to the IP
>    of the service container using iptables forwarding
> 3. This script is executing -inside- the network container. Because
>    the network container is linked to the service container, the network
>    container can read the IP of the service container (called private_server)
>    from its hosts file.
> 
> That is basically all that the network container does. How does this
> network container gets its ip?
> 
> For this I use the pipework script. That script creates a virtual network
> device inside the network container that is bridged with the network device
> of the host. Because of this it can access the DHCP service from the
> network.
> 
> The script waits until an IP is assigned to the container, and then exits.
> You can also read the IP from the log if you do docker logs
> 'container-name-or-id'.
> 
> Please let me know if anything is still unclear. Thanks for using my
> script!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jeroenpeeters/docker-network-containers/issues/2#issuecomment-75461706
> .

## 

---

Two Wheels Good, Four Wheels Bad

**Comment by jeroenpeeters** [comment]
Well, that's something you could easily check in the Dockerfile right?
